config/routes.rb
Socialapp::Application.routes.draw do
  resources :user_profiles

  root 'home#index'
  resources :users

end

app/models/user.rb
class User < ActiveRecord::Base
end

app/models/user_profile.rb
class UserProfile < ActiveRecord::Base
  belongs_to :user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
end

app/controllers/user_profiles_controller.rb
class UserProfilesController < ApplicationController
  before_action :set_user_profile, only: [:show, :edit, :update, :destroy]

  # GET /user_profiles
  # GET /user_profiles.json
  def index
    @user_profiles = UserProfile.all
  end

  # GET /user_profiles/1
  # GET /user_profiles/1.json
  def show
  end

  # GET /user_profiles/new
  def new
    @user_profile = UserProfile.new
  end

  # GET /user_profiles/1/edit
  def edit
  end

  # POST /user_profiles
  # POST /user_profiles.json
  def create
    @user_profile = UserProfile.new(user_profile_params)

    respond_to do |format|
      if @user_profile.save
        format.html { redirect_to @user_profile, notice: 'User profile was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user_profile }
      else
        format.html { render action: 'new' }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_profiles/1
  # PATCH/PUT /user_profiles/1.json
  def update
    respond_to do |format|
      if @user_profile.update(user_profile_params)
        format.html { redirect_to @user_profile, notice: 'User profile was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user_profile.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_profiles/1
  # DELETE /user_profiles/1.json
  def destroy
    @user_profile.destroy
    respond_to do |format|
      format.html { redirect_to user_profiles_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_profile
      @user_profile = UserProfile.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_profile_params
      params.require(:user_profile).permit(:starsign, :hobbies, :profile_pic, :user_id)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController 
	def index
		@users = User.all
	end	

	def new 
		@user = User.new
	end
	
	def create 
		@user = User.new(user_params)
		if @user.save 
			redirect_to users_path
		end	
	end	

	def show 
		@user = User.find(params[:id])
	end 
	
	def edit 
		@user = User.find (params[:id])	
	end

	def update
		@user = User.find(params[:id])
		if @user.update(user_params)
			redirect_to users_path
		end
	end

	def destroy
		@user = User.find(params[:id])
		@user.destroy
		redirect_to users_path

	end

	private 

	def user_params 
		params.require( :user).permit( :name, :email, :password, :phone)
	end	
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_profiles_helper.rb
module UserProfilesHelper
end

app/views/home/index.html.erb
<h1>Welcome to SocialApp</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Socialapp</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/user_profiles/_form.html.erb
<%= form_for(@user_profile) do |f| %>
  <% if @user_profile.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_profile.errors.count, "error") %> prohibited this user_profile from being saved:</h2>

      <ul>
      <% @user_profile.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :starsign %><br>
    <%= f.text_field :starsign %>
  </div>
  <div class="field">
    <%= f.label :hobbies %><br>
    <%= f.text_field :hobbies %>
  </div>
  <div class="field">
    <%= f.label :profile_pic %><br>
    <%= f.text_field :profile_pic %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.text_field :user_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_profiles/edit.html.erb
<h1>Editing user_profile</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_profile %> |
<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/index.html.erb
<h1>Listing user_profiles</h1>

<table>
  <thead>
    <tr>
      <th>Starsign</th>
      <th>Hobbies</th>
      <th>Profile pic</th>
      <th>User</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @user_profiles.each do |user_profile| %>
      <tr>
        <td><%= user_profile.starsign %></td>
        <td><%= user_profile.hobbies %></td>
        <td><%= user_profile.profile_pic %></td>
        <td><%= user_profile.user.name %></td>
        <td><%= link_to 'Show', user_profile %></td>
        <td><%= link_to 'Edit', edit_user_profile_path(user_profile) %></td>
        <td><%= link_to 'Destroy', user_profile, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User profile', new_user_profile_path %>

app/views/user_profiles/new.html.erb
<h1>New user_profile</h1>

<%= render 'form' %>

<%= link_to 'Back', user_profiles_path %>

app/views/user_profiles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Starsign:</strong>
  <%= @user_profile.starsign %>
</p>

<p>
  <strong>Hobbies:</strong>
  <%= @user_profile.hobbies %>
</p>

<p>
  <strong>Profile pic:</strong>
  <%= @user_profile.profile_pic %>
</p>

<p>
  <strong>User:</strong>
  <%= @user_profile.user.name %>
</p>

<%= link_to 'Edit', edit_user_profile_path(@user_profile) %> |
<%= link_to 'Back', user_profiles_path %>

app/views/users/edit.html.erb
<%= form_for @user do |f| %> 
	<p>Enter your name <%= f.text_field :name %></p>
	<p>Enter your email <%= f.text_field :email %></p>
	<p>Choose a password <%= f.password_field :password %></p>
	<p>Your phone number <%= f.text_field :phone %></p>
	<p><%= f.submit %></p>
<% end %>

app/views/users/index.html.erb
<h1>List of users</h1> 

<table> 
	<tr>
		<th>Name</th>
		<th>Email</th>
		<th>Phone</th>
		<th></th>
		<th></th>
	</tr>
	<tr>
		<% @users.each do |user| %>
		<tr>
			<td><%= link_to user.name, user_path(user) %></td>
			<td><%= user.email %></td>
			<td><%= user.phone %></td>
			<td><%= link_to "Edit", edit_user_path(user) %></td>
			<td><%= link_to "Delete", user, method: :delete %></td>
		</tr>
	<% end %> 
	</tr>
</table>
<br>


<%= link_to "Add new user", new_user_path %>

app/views/users/new.html.erb
<%= form_for @user do |f| %> 
	<p>Enter your name <%= f.text_field :name %></p>
	<p>Enter your email <%= f.text_field :email %></p>
	<p>Choose a password <%= f.password_field :password %></p>
	<p>Your phone number <%= f.text_field :phone %></p>
	<p><%= f.submit %></p>
<% end %>

app/views/users/show.html.erb
<h1> <%= @user.name %>'s Page</h1>

<strong>Email: </strong><%= @user.email %><br>
<strong>Phone: </strong><%= @user.phone %><br>

<%= link_to "Back to users page", users_path %>